name: landslide

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - rasterio
  - geopandas
  - scipy
  - matplotlib
  - pip
  - pip:
      - torch
      - torchvision
      - timm